---
ansibleuser:
  name: 'ansible'
  group: 'ansible'
  uid: 1000
  gid: 1000
  password: '{{ ansible_sudo_pass }}'
  pubkeys:
    - {key: '{{ ansibleuser_key }}'}

apache2:
  document_root: '/var/www/html'
  servername: 'www.example.com:80'
  vhosts_conf_dir: '/etc/httpd/conf.d/vhosts'
  vhosts:
    - {name: undefined,   conf_file: undefined,        document_root: "/var/www/undefined"   }  #vhostを使うなら設置
    - {name: example.com, conf_file: example.com.conf, document_root: "/var/www/example.com" }

database:
  name: 'db_name'
  root:
    password: '{{ db_root_pass }}'
  user:
    name: 'db_user'
    password: '{{ db_user_pass }}'
    priv: 'db_name.*:ALL'

git:
  version: '2.15.1'         #参照先 => https://www.kernel.org/pub/software/scm/git/
  src_dir: '/usr/local/src'
  bin_dir: '/usr/local/bin'

hostname:
  sethostname: 'www.example.com'

letsencrypt:
  certbot_path: '/usr/bin/certbot-auto'
  certificates:
    - { document_root: '/var/www/example.com/public/', domains: 'example.com,www.example.com', email: 'postmaster@example.com'}
    - { document_root: '/var/www/example.net/'       , domains: 'example.net,www.example.net', email: 'postmaster@example.net'}

logwatch:
  mailto: 'logwatch@example.com'
  detail: 'High'


mailserver:
  aliases: '/etc/postfix/aliases'
  virtual:
    mailbox_domains: '/var/spool/vmail'
    mailbox_base: '/var/spool/mail/vhosts'
    mailbox_maps: '/etc/postfix/vmailbox'
    alias_maps: '/etc/postfix/vmailbox_alias'
    minimum_uid: 100
    user:
      name: 'vmail'
      shell: '/bin/false'
      uid: '5001'
      gid: '5001'
  tls:
    smtpd_tls_cert_file: '/etc/pki/tls/certs/mailserver.crt'
    smtpd_tls_key_file: '/etc/pki/tls/certs/mailserver.key'
    smtpd_use_tls: yes
  dovecot:
    auth_passwdfile: '/etc/dovecot/passwd'
  mailaccount:
    - domain: 'example.com'
      account:
        - { localpart: 'postmaster', password: 'postmaster password' }
        - { localpart: 'test',       password: 'test password' }
        - { localpart: 'info',       password: 'info password' }

    - domain: 'example.net'
      account:
        - { localpart: 'postmaster', password: 'postmaster password' }
        - { localpart: 'test',       password: 'test password' }
        - { localpart: 'info',       password: 'info password' }
  mailtransfer:
    - { mailaccount: 'test@example.com', alias: 'test+example.com', transfer: 'postmaster@example.com, info@example.com'}
    - { mailaccount: 'test@example.net', alias: 'test+example.net', transfer: '"| /usr/bin/php  /path/to/mail.php"' }

ssh:
  port: '{{ ssh_port }}'

user:
  - { name: alice, password: "Alice's password", groups: '',          key: 'https://github.com/today4u.keys' }      # publicKey in github 
  - { name: bob,   password: "Bob's password",   groups: 'alice',     key: '{{ lookup("file","bob.pub") }}' }  # publicKey in  roles/users/files/bob.pub
#  - { name: carol, password: "Carol's password", groups: 'alice,bob', key: '{{ lookup("file","/home/carol/.ssh/id_rsa.pub") }}' } #belong to the group of Alice and Bob


