---
- name : 一般ユーザー追加
  user: 
    name: "{{ item.name }}"
    password: "{{ item.password |password_hash('sha512') }}"
    groups: '{{ item.groups }}'
    state: present
  with_items: '{{ user }}'
  when: user

- name: 一般ユーザー鍵設置
  authorized_key:
     user: '{{ item.name }}'
     state: present
     key: '{{ item.key }}'
  with_items: '{{ user }}'
  when: user

