---
- name: MariaDBインストール
  yum: name={{item}} state=latest
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel
    - MySQL-python
- name: MariaDB起動＆自動起動設定
  service: name=mariadb state=started enabled=yes


- name: my.cnf 関連
  lineinfile:
    dest: /etc/my.cnf
    state: present
    backup: yes
    insertafter: '{{ item.insertafter}}'
    line: '{{ item.line }}'
  with_items: 
    - insertafter: '^[mysqld]'
      line: 'character-set-server=utf8'
    - insertafter: '^[mysqld]'
      line: 'slow_query_log=ON'

